# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-10 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170610_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='shawtyurl',
            name='empty_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shawtyurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shawtyurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
