# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-14 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170610_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shawtyurl',
            name='empty_datetime',
        ),
        migrations.AlterField(
            model_name='shawtyurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
