# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20170614_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='shawtyurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
