# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-20 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20170615_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shawtyurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
